export default function getCountries() {
  return [
    { name: "fwc", value: "fwc" },
    { name: "qatar", value: "qat" },
    { name: "ecuador", value: "ecu" },
    { name: "senegal", value: "sen" },
    { name: "netherlands", value: "ned" },
    { name: "england", value: "eng" },
    { name: "iran", value: "irn" },
    { name: "united states", value: "usa" },
    { name: "wales", value: "wal" },
    { name: "argentina", value: "arg" },
    { name: "saudi arabia", value: "ksa" },
    { name: "mexico", value: "mex" },
    { name: "poland", value: "pol" },
    { name: "france", value: "fra" },
    { name: "australia", value: "aus" },
    { name: "denmark", value: "den" },
    { name: "tunisia", value: "tun" },
    { name: "spain", value: "esp" },
    { name: "costa rica", value: "crc" },
    { name: "germany", value: "ger" },
    { name: "japan", value: "jap" },
    { name: "belgium", value: "bel" },
    { name: "canada", value: "can" },
    { name: "marrocos", value: "mar" },
    { name: "croatia", value: "cro" },
    { name: "brazil", value: "bra" },
    { name: "serbia", value: "srb" },
    { name: "switzerland", value: "sui" },
    { name: "cameroon", value: "cmr" },
    { name: "portugal", value: "por" },
    { name: "ghana", value: "gha" },
    { name: "uruguay", value: "uru" },
    { name: "south korea", value: "kor" },
    { name: "special", value: "special" },
  ];
}
