name: Cl Test

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Verificar Código
      run: echo "Verificando o código..."

    - name: Testar Código
      run: echo "Testando o código..."

    - name: Implantação
      run: echo "Implantando o código..."
