name: Cl Test

on: [push]

concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Verificar Código
      run: echo "Verificando o código..."
      timeout-minutes: 2

    - name: Testar Código
      run: echo "Testando o código..."
      timeout-minutes: 2

    - name: Implantação
      run: echo "Implantando o código..."
      timeout-minutes: 2

    - name: Loop de test
      run: |
        # Loop infinito que aguarda 5 minutos (300 segundos)
        for ((i=0; i<120; i++)); do
          echo "Aguardando por 2 minutos..."
          sleep 1
        done
