name: Cl Test

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Verificar Código
      run: echo "Verificando o código..."
      timeout-minutes: 2

    - name: Testar Código
      run: echo "Testando o código..."
      timeout-minutes: 2

    - name: Implantação
      run: echo "Implantando o código..."
      timeout-minutes: 2

    - name: Loop de test
      run: |
        # Loop infinito que aguarda 5 minutos (300 segundos)
        for ((i=0; i<300; i++)); do
          echo "Aguardando por 5 minutos..."
          sleep 1
        done
