name: Cl Test

on: [push]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Output HeadRef
      run: echo '${{ github.head_ref }}'

    - name: Loop de test
      run: |
        # Loop infinito que aguarda 5 minutos (300 segundos)
        for ((i=0; i<120; i++)); do
          echo "Aguardando por 2 minutos..."
          sleep 1
        done
